services:
  db:
    image: postgres:16-alpine
    container_name: onlinecinema_postgres
    restart: always
    ports:
      - "5001:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - onlinecinema_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./src/OnlineCinema.Backend
      dockerfile: Dockerfile
    container_name: onlinecinema_backend
    restart: always
    ports:
      - "5000:80"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - onlinecinema_network
    volumes:
      - ./static:/app/static

volumes:
  postgres_data:
    driver: local

networks:
  onlinecinema_network:
    driver: bridge