server {
    listen 80;
    
    # Раздача фронтенда
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Проксирование запросов к API на бэкенд
    location /api/ {
        proxy_pass http://backend:80/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Проксирование Swagger (если нужно)
    location /swagger/ {
        proxy_pass http://backend:80/swagger/;
        proxy_set_header Host $host;
    }

    # Проксирование статики (картинки, видео)
    location /static/ {
        proxy_pass http://backend:80/static/;
        proxy_set_header Host $host;
    }
}